---
web:
  image: jimbojsb/wpengine-docker:0.2.2
  ports:
  - 80:80
  - 443:443
  links:
  - mysql
  volumes:
  - .:/www

mysql:
  image: mysql:5.6
  command: mysqld --user=root --verbose --skip-sync-frm --innodb_flush_log_at_trx_commit=0 --innodb-support-xa=0 --bind-address=0.0.0.0 --query-cache-type=1
  ports:
  - 3306:3306
  environment:
    MYSQL_ROOT_PASSWORD: root
    MYSQL_DATABASE: wpdev
    MYSQL_USER: wpdev
    MYSQL_PASSWORD: wpdev